all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    autoware_version: "2024.12"
    ros_distro: "humble"
    cuda_version: "12.3"
